#!/bin/sh
### BEGIN INIT INFO
# Provides:          install_dsi_driver_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Installs DSI Display driver
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting install_dsi_driver_once"
    cd /lib/modules/6.1.21-v8+ &&
    depmod && 
    modprobe WS_xinchDSI_Touch && 
    modprobe WS_xinchDSI_Screen &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
